module Api
  module V1
    module Agency
      # Bookings made by OTHER agencies on retreats created by this agency.
      # Gives the agency visibility into revenue generated by their retreats.
      class BillingController < BaseController
        # GET /api/v1/agency/billing
        def index
          my_retreat_ids = Retreat.where(created_by_organization: current_organization).pluck(:id)

          if my_retreat_ids.empty?
            return render json: {
              sales: [],
              meta: { page: 1, per_page: 25, total: 0, total_pages: 0 },
              summary: { total_count: 0, total_revenue_cents: 0, total_commission_cents: 0 }
            }
          end

          scope = Booking.where(retreat_id: my_retreat_ids)
                         .where.not(organization_id: current_organization.id)
                         .includes(:client, :organization, :retreat, :room_type, :hotel, experience: :hotel)
                         .order(created_at: :desc)

          render json: {
            sales: paginate(scope).map { |b| ApiSerializers.billing_sale(b) },
            meta: meta_for(scope),
            summary: summary(scope)
          }
        end

        private

        def summary(scope)
          active = scope.active
          total_revenue = active.sum(:amount_cents)
          total_commission = active.sum(:commission_cents)
          office_rate = PlatformSetting.first&.office_fee_rate || 0.02
          total_office = (total_revenue * office_rate).round
          {
            total_count: scope.count,
            total_revenue_cents: total_revenue,
            total_commission_cents: total_commission,
            total_net_cents: total_revenue - total_commission - total_office
          }
        end
      end
    end
  end
end
